"""init

Revision ID: 49a7238d3db4
Revises: 
Create Date: 2026-04-01 21:21:44.892199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a7238d3db4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='模型代码'),
    sa.Column('model_type', sa.Enum('CHAT', 'IMAGE_GEN', 'IMAGE_EDIT', 'VIDEO_GEN', 'AUDIO_GEN', name='modeltype'), nullable=False, comment='模型类型'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='提供商'),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True, comment='API端点'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API密钥'),
    sa.Column('quota_cost', sa.BigInteger(), nullable=False, comment='单次扣费额度'),
    sa.Column('config', sa.Text(), nullable=True, comment='模型配置JSON'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_ai_model_id'), 'ai_model', ['id'], unique=False)
    op.create_table('task_flow',
    sa.Column('name', sa.String(length=200), nullable=False, comment='模板名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='模板代码'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('flow_config', sa.JSON(), nullable=False, comment='编排配置JSON'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='缩略图'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统预设'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_task_flow_id'), 'task_flow', ['id'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=False, comment='状态'),
    sa.Column('register_ip', sa.String(length=50), nullable=True, comment='注册IP'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('ai_task',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('task_name', sa.String(length=200), nullable=True, comment='任务名称'),
    sa.Column('task_type', sa.Enum('TEXT_TO_IMAGE', 'IMAGE_TO_IMAGE', 'IMAGE_TO_VIDEO', 'TEXT_TO_VIDEO', 'CHAT', 'WORKFLOW', name='tasktype'), nullable=False, comment='任务类型'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRY', 'CANCELLED', 'TIMEOUT', name='taskstatus'), nullable=False, comment='状态'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='模型ID'),
    sa.Column('input_params', sa.JSON(), nullable=True, comment='输入参数'),
    sa.Column('output_urls', sa.JSON(), nullable=True, comment='输出文件URL列表'),
    sa.Column('quota_cost', sa.BigInteger(), nullable=False, comment='消耗额度'),
    sa.Column('started_at', sa.String(length=20), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.String(length=20), nullable=True, comment='完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='重试次数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_model.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_task_id'), 'ai_task', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('session_id', sa.String(length=100), nullable=False, comment='会话ID'),
    sa.Column('session_name', sa.String(length=200), nullable=True, comment='会话名称'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatrole'), nullable=False, comment='角色'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('model_code', sa.String(length=50), nullable=True, comment='模型代码'),
    sa.Column('meta_info', sa.JSON(), nullable=True, comment='元数据'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_table('material',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='素材名称'),
    sa.Column('material_type', sa.Enum('IMAGE', 'VIDEO', 'TEXT', 'AUDIO', name='materialtype'), nullable=False, comment='素材类型'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文件URL'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小'),
    sa.Column('file_format', sa.String(length=20), nullable=True, comment='文件格式'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('tags', sa.String(length=500), nullable=True, comment='标签'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='缩略图URL'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    op.create_table('order',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='订单号'),
    sa.Column('payment_channel', sa.Enum('ALIPAY', 'WECHAT', name='paymentchannel'), nullable=False, comment='支付渠道'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='支付金额'),
    sa.Column('quota_amount', sa.BigInteger(), nullable=False, comment='额度数量'),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False, comment='状态'),
    sa.Column('paid_at', sa.String(length=20), nullable=True, comment='支付时间'),
    sa.Column('transaction_id', sa.String(length=100), nullable=True, comment='第三方支付流水号'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('quota_log',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('log_type', sa.Enum('DEDUCT', 'RECHARGE', 'GIFT', 'REFUND', name='quotalogtype'), nullable=False, comment='日志类型'),
    sa.Column('amount', sa.BigInteger(), nullable=False, comment='变动金额'),
    sa.Column('balance_before', sa.BigInteger(), nullable=False, comment='变动前余额'),
    sa.Column('balance_after', sa.BigInteger(), nullable=False, comment='变动后余额'),
    sa.Column('biz_type', sa.String(length=50), nullable=True, comment='业务类型'),
    sa.Column('biz_id', sa.Integer(), nullable=True, comment='业务ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_log_id'), 'quota_log', ['id'], unique=False)
    op.create_table('user_quota',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('free_quota', sa.BigInteger(), nullable=False, comment='免费额度'),
    sa.Column('remaining_quota', sa.BigInteger(), nullable=False, comment='剩余额度'),
    sa.Column('total_recharge', sa.BigInteger(), nullable=False, comment='总充值额度'),
    sa.Column('total_used', sa.BigInteger(), nullable=False, comment='总使用额度'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_quota_id'), 'user_quota', ['id'], unique=False)
    op.create_table('task_item',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='主任务ID'),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('step_name', sa.String(length=100), nullable=False, comment='步骤名称'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED', name='taskitemstatus'), nullable=False, comment='状态'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='模型ID'),
    sa.Column('input_params', sa.JSON(), nullable=True, comment='输入参数'),
    sa.Column('output_urls', sa.JSON(), nullable=True, comment='输出URL'),
    sa.Column('quota_cost', sa.BigInteger(), nullable=False, comment='消耗额度'),
    sa.Column('started_at', sa.String(length=20), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.String(length=20), nullable=True, comment='完成时间'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ai_model.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['ai_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_item_id'), 'task_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_item_id'), table_name='task_item')
    op.drop_table('task_item')
    op.drop_index(op.f('ix_user_quota_id'), table_name='user_quota')
    op.drop_table('user_quota')
    op.drop_index(op.f('ix_quota_log_id'), table_name='quota_log')
    op.drop_table('quota_log')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.drop_table('material')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_ai_task_id'), table_name='ai_task')
    op.drop_table('ai_task')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_task_flow_id'), table_name='task_flow')
    op.drop_table('task_flow')
    op.drop_index(op.f('ix_ai_model_id'), table_name='ai_model')
    op.drop_table('ai_model')
    # ### end Alembic commands ###
