"""fix started_at length

Revision ID: c339b65def9e
Revises: da9041154e13
Create Date: 2026-04-01 23:51:53.445493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c339b65def9e'
down_revision: Union[str, None] = 'da9041154e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_task', 'started_at',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_comment='开始时间',
               existing_nullable=True)
    op.alter_column('ai_task', 'completed_at',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_comment='完成时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_task', 'completed_at',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('ai_task', 'started_at',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_comment='开始时间',
               existing_nullable=True)
    # ### end Alembic commands ###
