"""add external_task_id to ai_task

Revision ID: da9041154e13
Revises: 49a7238d3db4
Create Date: 2026-04-01 23:49:58.377525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9041154e13'
down_revision: Union[str, None] = '49a7238d3db4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_task', sa.Column('external_task_id', sa.String(length=100), nullable=True, comment='外部任务ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_task', 'external_task_id')
    # ### end Alembic commands ###
